{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "eef28e56",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-06 14:08:29,421 [INFO] Tiendas encontradas: ['jumbo', 'exito', 'olimpica', 'alkosto']\n",
      "2026-03-06 14:08:29,434 [INFO] ============================================================\n",
      "2026-03-06 14:08:29,435 [INFO] SCRAPING: JUMBO (https://www.jumbocolombia.com)\n",
      "2026-03-06 14:08:29,436 [INFO] ============================================================\n",
      "2026-03-06 14:08:29,436 [INFO] [1/5] Catalog API para JUMBO...\n",
      "2026-03-06 14:08:29,437 [INFO]   [Catalog] jumbo path='frutas-y-verduras' from=0\n",
      "2026-03-06 14:08:30,187 [INFO]     ✓ 12 productos (frutas-y-verduras)\n",
      "2026-03-06 14:08:30,187 [INFO]   [Catalog] jumbo path='lacteos-huevos-y-refrigerados' from=0\n",
      "2026-03-06 14:08:37,833 [INFO]     ✓ 3 productos (lacteos-huevos-y-refrigerados)\n",
      "2026-03-06 14:08:37,833 [INFO]   [Catalog] jumbo path='despensa' from=0\n",
      "2026-03-06 14:08:38,570 [INFO]     ✓ 42 productos (despensa)\n",
      "2026-03-06 14:08:38,570 [INFO]   [Catalog] jumbo path='carnes-y-pescados' from=0\n",
      "2026-03-06 14:08:38,834 [INFO]   [Catalog] jumbo path='bebidas' from=0\n",
      "2026-03-06 14:08:41,600 [INFO]   [Catalog] jumbo path='bebidas' from=50\n",
      "2026-03-06 14:08:43,917 [INFO]   [Catalog] jumbo path='bebidas' from=100\n",
      "2026-03-06 14:08:44,167 [INFO]     ✓ 100 productos (bebidas)\n",
      "2026-03-06 14:08:44,183 [INFO] → 157 productos totales de JUMBO\n",
      "\n",
      "2026-03-06 14:08:44,183 [INFO] ============================================================\n",
      "2026-03-06 14:08:44,183 [INFO] SCRAPING: EXITO (https://www.exito.com)\n",
      "2026-03-06 14:08:44,183 [INFO] ============================================================\n",
      "2026-03-06 14:08:44,183 [INFO] [1/5] Catalog API para EXITO...\n",
      "2026-03-06 14:08:44,187 [INFO]   [Catalog] exito path='mercado/frutas-y-verduras' from=0\n",
      "2026-03-06 14:08:47,002 [INFO]   [Catalog] exito path='mercado/frutas-y-verduras' from=50\n",
      "2026-03-06 14:08:49,800 [INFO]   [Catalog] exito path='mercado/frutas-y-verduras' from=100\n",
      "2026-03-06 14:08:52,805 [INFO]     ✓ 150 productos (frutas-y-verduras)\n",
      "2026-03-06 14:08:52,805 [INFO]   [Catalog] exito path='mercado/lacteos-huevos-y-refrigerados' from=0\n",
      "2026-03-06 14:08:58,799 [INFO]   [Catalog] exito path='mercado/lacteos-huevos-y-refrigerados' from=50\n",
      "2026-03-06 14:09:01,633 [INFO]   [Catalog] exito path='mercado/lacteos-huevos-y-refrigerados' from=100\n",
      "2026-03-06 14:09:07,370 [INFO]     ✓ 150 productos (lacteos-huevos-y-refrigerados)\n",
      "2026-03-06 14:09:07,370 [INFO]   [Catalog] exito path='mercado/despensa' from=0\n",
      "2026-03-06 14:09:09,749 [INFO]   [Catalog] exito path='mercado/despensa' from=50\n",
      "2026-03-06 14:09:12,683 [INFO]   [Catalog] exito path='mercado/despensa' from=100\n",
      "2026-03-06 14:09:19,099 [INFO]     ✓ 150 productos (despensa)\n",
      "2026-03-06 14:09:19,099 [INFO]   [Catalog] exito path='mercado/carnes-y-pescados' from=0\n",
      "2026-03-06 14:09:19,651 [INFO]   [Catalog] exito path='mercado/bebidas' from=0\n",
      "2026-03-06 14:09:22,501 [INFO]   [Catalog] exito path='mercado/bebidas' from=50\n",
      "2026-03-06 14:09:26,654 [INFO]   [Catalog] exito path='mercado/bebidas' from=100\n",
      "2026-03-06 14:09:29,633 [INFO]     ✓ 150 productos (bebidas)\n",
      "2026-03-06 14:09:29,633 [INFO] → 600 productos totales de EXITO\n",
      "\n",
      "2026-03-06 14:09:29,633 [INFO] ============================================================\n",
      "2026-03-06 14:09:29,633 [INFO] SCRAPING: OLIMPICA (https://www.olimpica.com)\n",
      "2026-03-06 14:09:29,633 [INFO] ============================================================\n",
      "2026-03-06 14:09:29,633 [INFO] [1/5] Catalog API para OLIMPICA...\n",
      "2026-03-06 14:09:29,633 [INFO]   [Catalog] olimpica path='supermercado/frutas-y-verduras' from=0\n",
      "2026-03-06 14:09:32,465 [INFO]   [Catalog] olimpica path='supermercado/frutas-y-verduras' from=50\n",
      "2026-03-06 14:09:34,982 [INFO]   [Catalog] olimpica path='supermercado/frutas-y-verduras' from=100\n",
      "2026-03-06 14:09:41,898 [INFO]     ✓ 150 productos (frutas-y-verduras)\n",
      "2026-03-06 14:09:41,898 [INFO]   [Catalog] olimpica path='supermercado/lacteos-y-huevos' from=0\n",
      "2026-03-06 14:09:42,181 [INFO]   [Catalog] olimpica path='supermercado/despensa' from=0\n",
      "2026-03-06 14:09:44,562 [INFO]   [Catalog] olimpica path='supermercado/despensa' from=50\n",
      "2026-03-06 14:09:47,205 [INFO]   [Catalog] olimpica path='supermercado/despensa' from=100\n",
      "2026-03-06 14:09:49,577 [INFO]     ✓ 150 productos (despensa)\n",
      "2026-03-06 14:09:49,578 [INFO]   [Catalog] olimpica path='supermercado/carnes' from=0\n",
      "2026-03-06 14:09:53,248 [INFO]   [Catalog] olimpica path='supermercado/carnes' from=50\n",
      "2026-03-06 14:09:56,396 [INFO]   [Catalog] olimpica path='supermercado/carnes' from=100\n",
      "2026-03-06 14:10:02,216 [INFO]     ✓ 150 productos (carnes)\n",
      "2026-03-06 14:10:02,216 [INFO]   [Catalog] olimpica path='supermercado/bebidas' from=0\n",
      "2026-03-06 14:10:04,896 [INFO]   [Catalog] olimpica path='supermercado/bebidas' from=50\n",
      "2026-03-06 14:10:07,600 [INFO]   [Catalog] olimpica path='supermercado/bebidas' from=100\n",
      "2026-03-06 14:10:10,011 [INFO]     ✓ 150 productos (bebidas)\n",
      "2026-03-06 14:10:10,011 [INFO] → 600 productos totales de OLIMPICA\n",
      "\n",
      "2026-03-06 14:10:10,011 [INFO] ============================================================\n",
      "2026-03-06 14:10:10,011 [INFO] SCRAPING: ALKOSTO (https://www.alkosto.com)\n",
      "2026-03-06 14:10:10,011 [INFO] ============================================================\n",
      "2026-03-06 14:10:10,011 [INFO] [1/5] Catalog API para ALKOSTO...\n",
      "2026-03-06 14:10:10,011 [INFO]   [Catalog] alkosto path='supermercado/despensa' from=0\n",
      "2026-03-06 14:10:11,664 [INFO]   [Catalog] alkosto path='supermercado/bebidas' from=0\n",
      "2026-03-06 14:10:13,129 [INFO]   [Catalog] alkosto path='supermercado/lacteos-y-refrigerados' from=0\n",
      "2026-03-06 14:10:14,597 [INFO]   [Catalog] alkosto path='supermercado/frutas-y-verduras' from=0\n",
      "2026-03-06 14:10:16,048 [INFO]   [Catalog] alkosto path='supermercado/carnes-y-pescados' from=0\n",
      "2026-03-06 14:10:17,497 [INFO] [2/5] Intelligent Search para ALKOSTO...\n",
      "2026-03-06 14:10:17,497 [INFO]   [IntelligentSearch] alkosto query='frutas' from=0\n",
      "2026-03-06 14:10:18,949 [INFO]   [IntelligentSearch] alkosto query='leche' from=0\n",
      "2026-03-06 14:10:20,595 [INFO]   [IntelligentSearch] alkosto query='arroz' from=0\n",
      "2026-03-06 14:10:22,165 [INFO]   [IntelligentSearch] alkosto query='pollo' from=0\n",
      "2026-03-06 14:10:23,678 [INFO]   [IntelligentSearch] alkosto query='agua' from=0\n",
      "2026-03-06 14:10:25,230 [INFO] [3/5] Dominio VTEX alternativo para ALKOSTO...\n",
      "2026-03-06 14:10:25,230 [INFO] [4/5] __NEXT_DATA__ para ALKOSTO...\n",
      "2026-03-06 14:10:25,230 [INFO]   [NextData] alkosto url='https://www.alkosto.com/supermercado/despensa'\n",
      "2026-03-06 14:10:26,629 [INFO]   [NextData] alkosto url='https://www.alkosto.com/supermercado/bebidas'\n",
      "2026-03-06 14:10:27,476 [INFO] [5/5] Sitemap + scraping HTML para ALKOSTO...\n",
      "2026-03-06 14:10:27,476 [INFO]   [Sitemap] Probando https://www.alkosto.com/sitemap.xml\n",
      "2026-03-06 14:10:27,824 [INFO]   [Sitemap] Sub-sitemap de productos: https://www.alkosto.com/sitemap-productos.xml\n",
      "2026-03-06 14:10:30,413 [INFO]   [Sitemap] 200 URLs de productos encontradas\n",
      "2026-03-06 14:11:15,628 [INFO]   [Sitemap] Procesando 20/200...\n",
      "2026-03-06 14:12:22,795 [INFO]   [Sitemap] Procesando 40/200...\n",
      "2026-03-06 14:13:19,333 [INFO]   [Sitemap] Procesando 60/200...\n",
      "2026-03-06 14:14:07,933 [INFO]   [Sitemap] Procesando 80/200...\n",
      "2026-03-06 14:15:14,898 [INFO]   [Sitemap] Procesando 100/200...\n",
      "2026-03-06 14:16:18,713 [INFO]   [Sitemap] Procesando 120/200...\n",
      "2026-03-06 14:17:00,911 [INFO]   [Sitemap] Procesando 140/200...\n",
      "2026-03-06 14:18:09,529 [INFO]   [Sitemap] Procesando 160/200...\n",
      "2026-03-06 14:18:48,054 [INFO]   [Sitemap] Procesando 180/200...\n",
      "2026-03-06 14:19:35,187 [INFO] → 0 productos totales de ALKOSTO\n",
      "\n",
      "2026-03-06 14:19:35,490 [INFO] Duplicados eliminados: 1357 → 1353 registros\n",
      "2026-03-06 14:19:35,492 [INFO] \n",
      "============================================================\n",
      "2026-03-06 14:19:35,492 [INFO] RESUMEN FINAL\n",
      "2026-03-06 14:19:35,493 [INFO] ============================================================\n",
      "2026-03-06 14:19:35,493 [INFO] Total productos únicos: 1353\n",
      "2026-03-06 14:19:35,520 [INFO] Productos por tienda:\n",
      "tienda\n",
      "exito       600\n",
      "olimpica    596\n",
      "jumbo       157\n",
      "2026-03-06 14:19:35,569 [INFO] Rango de precios por tienda:\n",
      "          count    min        max      mean\n",
      "tienda                                     \n",
      "exito       600  420.0    65325.0   10577.0\n",
      "jumbo       157    0.0  1128900.0  132437.0\n",
      "olimpica    596  950.0   149500.0   14224.0\n",
      "2026-03-06 14:19:35,574 [INFO] \n",
      "Primeras filas:\n",
      "  tienda          categoria                                                        nombre      marca   precio  precio_lista producto_id                                                                                           url_producto\n",
      "0  jumbo  frutas-y-verduras  Limpiador Desinfectante Frutas y Verduras Binner Verde 500ml     BINNER   8792.0       10990.0      321625           https://www.jumbocolombia.com/limpiador-desinfectante-frutas-y-verduras-binner-verde-500ml/p\n",
      "1  jumbo  frutas-y-verduras    Limpiador Desinfectante Frutas y Verduras Binner Verde 1lt     BINNER  14312.0       17890.0      321630             https://www.jumbocolombia.com/limpiador-desinfectante-frutas-y-verduras-binner-verde-1lt/p\n",
      "2  jumbo  frutas-y-verduras       Limpiador Ecohome ecológico de frutas y verduras x500ml   ECOFLORA  17600.0       22000.0       28683                         https://www.jumbocolombia.com/limpiador-de-frutas-y-verduras-ecohome-x-500ml/p\n",
      "3  jumbo  frutas-y-verduras  Limpiador Desinfectante Frutas y Verduras Binner Verde 500Ml     BINNER  15900.0       15900.0    20098640  https://www.jumbocolombia.com/limpiador-desinfectante-frutas-y-verduras-binner-verde-500ml-20098640/p\n",
      "4  jumbo  frutas-y-verduras                                                  guineo verde   A GRANEL   4980.0        4980.0       46261                                                          https://www.jumbocolombia.com/platano-verde/p\n",
      "5  jumbo  frutas-y-verduras                               Semillas Orgánicas brócoli x3gr        ONC   9990.0        9990.0      236262                                      https://www.jumbocolombia.com/semillas-organicas-onc-brocoli-3g/p\n",
      "6  jumbo  frutas-y-verduras                             Yuca Sal Marina 120 grs Natuchips  NATUCHIPS   8590.0        8590.0      396756                                      https://www.jumbocolombia.com/yuca-sal-marina-120-grs-natuchips/p\n",
      "7  jumbo  frutas-y-verduras                          Semillas orgánicas Onc pak choi x3gr        ONC   9590.0        9590.0      236257                                     https://www.jumbocolombia.com/semillas-organicas-onc-pak-choi-3g/p\n",
      "8  jumbo  frutas-y-verduras                        Semillas orgánicas Onc col mizuna x3gr        ONC   9590.0        9590.0      236297                                  https://www.jumbocolombia.com/semillas-organicas-onc-col-mizuna-3-g/p\n",
      "9  jumbo  frutas-y-verduras                        Tomate san Marzano Koshcampo x 1000 gr  KOSHCAMPO  21490.0       21490.0      243925                                 https://www.jumbocolombia.com/tomate-san-marzano-koshcampo-x-1000-gr/p\n",
      "2026-03-06 14:19:35,619 [INFO] \n",
      "Datos guardados en: productos_supermercados.csv\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Web Scraper para Supermercados Colombianos — v3\n",
    "================================================\n",
    "Extrae productos de: Jumbo, Éxito, Olímpica, Alkosto.\n",
    "\n",
    "Usa múltiples estrategias por tienda:\n",
    "  - APIs VTEX (Catalog + Intelligent Search)\n",
    "  - Dominio VTEX alternativo (*.vtex.app) para tiendas con protección\n",
    "  - Scraping de __NEXT_DATA__ embebido en HTML\n",
    "  - Sitemap XML + scraping individual de productos\n",
    "\n",
    "Dependencias:\n",
    "    pip install requests pandas lxml\n",
    "\n",
    "Uso:\n",
    "    python scraper_supermercados.py\n",
    "\"\"\"\n",
    "\n",
    "import re\n",
    "import json\n",
    "import time\n",
    "import logging\n",
    "import requests\n",
    "import pandas as pd\n",
    "from typing import Optional\n",
    "from xml.etree import ElementTree\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Configuración\n",
    "# ---------------------------------------------------------------------------\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s [%(levelname)s] %(message)s\",\n",
    ")\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "ARCHIVO_LISTA = \"lista_supermercado.txt\"\n",
    "\n",
    "PRODUCTOS_POR_PAGINA = 50\n",
    "MAX_PRODUCTOS_POR_CATEGORIA = 150\n",
    "DELAY_ENTRE_REQUESTS = 1.5\n",
    "\n",
    "# Máximo de productos a extraer del sitemap (para Alkosto)\n",
    "MAX_SITEMAP_PRODUCTS = 200\n",
    "\n",
    "HEADERS_BASE = {\n",
    "    \"User-Agent\": (\n",
    "        \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) \"\n",
    "        \"AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\"\n",
    "    ),\n",
    "    \"Accept\": \"application/json\",\n",
    "    \"Accept-Language\": \"es-CO,es;q=0.9\",\n",
    "}\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Utilidades\n",
    "# ---------------------------------------------------------------------------\n",
    "def leer_urls(filepath: str) -> dict[str, str]:\n",
    "    \"\"\"Lee el archivo .txt y devuelve {nombre_tienda: url}.\"\"\"\n",
    "    tiendas: dict[str, str] = {}\n",
    "    with open(filepath, encoding=\"utf-8\") as f:\n",
    "        contenido = f.read()\n",
    "\n",
    "    bloques = re.split(r\"\\n\\s*\\n\", contenido.strip())\n",
    "    for bloque in bloques:\n",
    "        lineas = [l.strip() for l in bloque.strip().splitlines() if l.strip()]\n",
    "        if len(lineas) >= 2:\n",
    "            nombre = re.sub(\n",
    "                r\"['\\u2019]s\\s+website\\s*:?\\s*$\", \"\", lineas[0], flags=re.IGNORECASE\n",
    "            ).strip()\n",
    "            url = lineas[1].rstrip(\"/\")\n",
    "            tiendas[nombre.lower()] = url\n",
    "    logger.info(\"Tiendas encontradas: %s\", list(tiendas.keys()))\n",
    "    return tiendas\n",
    "\n",
    "\n",
    "def hacer_request(\n",
    "    url: str,\n",
    "    params: dict = None,\n",
    "    headers: dict = None,\n",
    "    accept_206: bool = False,\n",
    "    accept_html: bool = False,\n",
    ") -> Optional[dict | list | str]:\n",
    "    \"\"\"\n",
    "    Hace un GET request con reintentos.\n",
    "    - accept_206: Acepta HTTP 206 (Partial Content) como válido — VTEX lo usa.\n",
    "    - accept_html: Retorna texto en vez de JSON.\n",
    "    \"\"\"\n",
    "    _headers = {**HEADERS_BASE, **(headers or {})}\n",
    "    valid_codes = {200}\n",
    "    if accept_206:\n",
    "        valid_codes.add(206)\n",
    "\n",
    "    for intento in range(3):\n",
    "        try:\n",
    "            resp = requests.get(url, params=params, headers=_headers, timeout=30)\n",
    "\n",
    "            if resp.status_code in valid_codes:\n",
    "                if accept_html:\n",
    "                    return resp.text\n",
    "                try:\n",
    "                    return resp.json()\n",
    "                except requests.exceptions.JSONDecodeError:\n",
    "                    if accept_html:\n",
    "                        return resp.text\n",
    "                    logger.warning(\"  Respuesta no es JSON en %s\", url)\n",
    "                    return None\n",
    "\n",
    "            elif resp.status_code == 429:\n",
    "                logger.warning(\"  Rate limited (429). Esperando 10s...\")\n",
    "                time.sleep(10)\n",
    "            elif resp.status_code == 404:\n",
    "                logger.debug(\"  404 Not Found: %s\", url)\n",
    "                return None\n",
    "            else:\n",
    "                logger.warning(\n",
    "                    \"  HTTP %d en %s (intento %d/3)\", resp.status_code, url, intento + 1\n",
    "                )\n",
    "        except requests.exceptions.JSONDecodeError:\n",
    "            logger.warning(\"  Respuesta no es JSON en %s\", url)\n",
    "            return None\n",
    "        except requests.exceptions.RequestException as e:\n",
    "            logger.error(\"  Error de conexión: %s\", e)\n",
    "\n",
    "        time.sleep(DELAY_ENTRE_REQUESTS * (intento + 1))\n",
    "    return None\n",
    "\n",
    "\n",
    "def extraer_producto_vtex(prod: dict, tienda: str, categoria: str, base_url: str) -> Optional[dict]:\n",
    "    \"\"\"Extrae datos de un producto VTEX (estructura estándar).\"\"\"\n",
    "    nombre = prod.get(\"productName\") or prod.get(\"nameComplete\") or prod.get(\"name\", \"\")\n",
    "    if not nombre:\n",
    "        return None\n",
    "\n",
    "    marca = prod.get(\"brand\", \"\")\n",
    "    link = prod.get(\"link\", prod.get(\"linkText\", \"\"))\n",
    "    prod_id = prod.get(\"productId\", \"\")\n",
    "\n",
    "    precio = None\n",
    "    precio_lista = None\n",
    "    try:\n",
    "        item = prod[\"items\"][0]\n",
    "        seller = item[\"sellers\"][0]\n",
    "        offer = seller[\"commertialOffer\"]\n",
    "        precio = offer.get(\"Price\")\n",
    "        precio_lista = offer.get(\"ListPrice\")\n",
    "    except (KeyError, IndexError, TypeError):\n",
    "        # Intentar estructura alternativa (priceRange)\n",
    "        try:\n",
    "            rango = prod[\"priceRange\"][\"sellingPrice\"]\n",
    "            precio = rango.get(\"lowPrice\")\n",
    "            rango_lista = prod[\"priceRange\"].get(\"listPrice\", {})\n",
    "            precio_lista = rango_lista.get(\"lowPrice\")\n",
    "        except (KeyError, TypeError):\n",
    "            pass\n",
    "\n",
    "    url_producto = \"\"\n",
    "    if link:\n",
    "        if link.startswith(\"http\"):\n",
    "            url_producto = link\n",
    "        elif link.startswith(\"/\"):\n",
    "            url_producto = f\"{base_url}{link}\"\n",
    "        else:\n",
    "            url_producto = f\"{base_url}/{link}\"\n",
    "\n",
    "    return {\n",
    "        \"tienda\": tienda,\n",
    "        \"categoria\": categoria,\n",
    "        \"nombre\": nombre,\n",
    "        \"marca\": marca,\n",
    "        \"precio\": precio,\n",
    "        \"precio_lista\": precio_lista,\n",
    "        \"producto_id\": str(prod_id),\n",
    "        \"url_producto\": url_producto,\n",
    "    }\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Estrategia 1: VTEX Catalog API (acepta 206)\n",
    "# ---------------------------------------------------------------------------\n",
    "def buscar_vtex_catalog(\n",
    "    base_url: str, categoria_path: str, tienda: str, categoria: str\n",
    ") -> list[dict]:\n",
    "    productos = []\n",
    "    offset = 0\n",
    "\n",
    "    while offset < MAX_PRODUCTOS_POR_CATEGORIA:\n",
    "        url = f\"{base_url}/api/catalog_system/pub/products/search/{categoria_path}\"\n",
    "        params = {\"_from\": offset, \"_to\": offset + PRODUCTOS_POR_PAGINA - 1}\n",
    "        logger.info(\"  [Catalog] %s path='%s' from=%d\", tienda, categoria_path, offset)\n",
    "\n",
    "        data = hacer_request(url, params=params, accept_206=True)\n",
    "\n",
    "        if not data or not isinstance(data, list) or len(data) == 0:\n",
    "            break\n",
    "\n",
    "        for prod in data:\n",
    "            item = extraer_producto_vtex(prod, tienda, categoria, base_url)\n",
    "            if item:\n",
    "                productos.append(item)\n",
    "\n",
    "        if len(data) < PRODUCTOS_POR_PAGINA:\n",
    "            break\n",
    "\n",
    "        offset += PRODUCTOS_POR_PAGINA\n",
    "        time.sleep(DELAY_ENTRE_REQUESTS)\n",
    "\n",
    "    return productos\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Estrategia 2: VTEX Intelligent Search API\n",
    "# ---------------------------------------------------------------------------\n",
    "def buscar_vtex_intelligent_search(\n",
    "    base_url: str, query: str, tienda: str, categoria: str\n",
    ") -> list[dict]:\n",
    "    productos = []\n",
    "    offset = 0\n",
    "\n",
    "    while offset < MAX_PRODUCTOS_POR_CATEGORIA:\n",
    "        url = f\"{base_url}/api/io/_v/api/intelligent-search/product_search/\"\n",
    "        params = {\n",
    "            \"query\": query,\n",
    "            \"from\": offset,\n",
    "            \"to\": offset + PRODUCTOS_POR_PAGINA - 1,\n",
    "            \"hideUnavailableItems\": \"false\",\n",
    "        }\n",
    "        logger.info(\"  [IntelligentSearch] %s query='%s' from=%d\", tienda, query, offset)\n",
    "        data = hacer_request(url, params=params, accept_206=True)\n",
    "\n",
    "        if not data or not isinstance(data, dict) or \"products\" not in data:\n",
    "            break\n",
    "\n",
    "        items = data[\"products\"]\n",
    "        if not items:\n",
    "            break\n",
    "\n",
    "        for prod in items:\n",
    "            item = extraer_producto_vtex(prod, tienda, categoria, base_url)\n",
    "            if item:\n",
    "                productos.append(item)\n",
    "\n",
    "        if len(items) < PRODUCTOS_POR_PAGINA:\n",
    "            break\n",
    "\n",
    "        offset += PRODUCTOS_POR_PAGINA\n",
    "        time.sleep(DELAY_ENTRE_REQUESTS)\n",
    "\n",
    "    return productos\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Estrategia 3: __NEXT_DATA__ scraping\n",
    "# ---------------------------------------------------------------------------\n",
    "def buscar_nextdata(base_url: str, path: str, tienda: str, categoria: str) -> list[dict]:\n",
    "    productos = []\n",
    "    url = f\"{base_url}{path}\"\n",
    "    logger.info(\"  [NextData] %s url='%s'\", tienda, url)\n",
    "\n",
    "    html = hacer_request(\n",
    "        url, headers={\"Accept\": \"text/html\"}, accept_206=True, accept_html=True\n",
    "    )\n",
    "    if not html or not isinstance(html, str):\n",
    "        return productos\n",
    "\n",
    "    match = re.search(\n",
    "        r'<script\\s+id=\"__NEXT_DATA__\"\\s+type=\"application/json\">(.*?)</script>',\n",
    "        html,\n",
    "        re.DOTALL,\n",
    "    )\n",
    "    if not match:\n",
    "        return productos\n",
    "\n",
    "    try:\n",
    "        next_data = json.loads(match.group(1))\n",
    "    except json.JSONDecodeError:\n",
    "        return productos\n",
    "\n",
    "    page_props = next_data.get(\"props\", {}).get(\"pageProps\", {})\n",
    "\n",
    "    def encontrar_productos(obj, depth=0):\n",
    "        if depth > 6:\n",
    "            return []\n",
    "        items = []\n",
    "        if isinstance(obj, dict):\n",
    "            for key, val in obj.items():\n",
    "                if isinstance(val, list) and len(val) > 0 and isinstance(val[0], dict):\n",
    "                    if any(\n",
    "                        k in val[0]\n",
    "                        for k in (\"productName\", \"productId\", \"nameComplete\")\n",
    "                    ):\n",
    "                        items.extend(val)\n",
    "                    elif \"product\" in key.lower():\n",
    "                        items.extend(val)\n",
    "                elif isinstance(val, dict):\n",
    "                    items.extend(encontrar_productos(val, depth + 1))\n",
    "        return items\n",
    "\n",
    "    raw = encontrar_productos(page_props)\n",
    "    for prod in raw:\n",
    "        item = extraer_producto_vtex(prod, tienda, categoria, base_url)\n",
    "        if item:\n",
    "            productos.append(item)\n",
    "\n",
    "    return productos\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Estrategia 4: Sitemap XML → scraping individual (para Alkosto)\n",
    "# ---------------------------------------------------------------------------\n",
    "def obtener_urls_sitemap(base_url: str) -> list[str]:\n",
    "    \"\"\"Obtiene URLs de productos del sitemap.xml.\"\"\"\n",
    "    urls_producto = []\n",
    "\n",
    "    # Intentar sitemap principal\n",
    "    for sitemap_path in [\"/sitemap.xml\", \"/sitemap_products.xml\", \"/sitemap/sitemap.xml\"]:\n",
    "        url = f\"{base_url}{sitemap_path}\"\n",
    "        logger.info(\"  [Sitemap] Probando %s\", url)\n",
    "        html = hacer_request(url, headers={\"Accept\": \"application/xml, text/xml\"}, accept_html=True)\n",
    "        if not html or not isinstance(html, str):\n",
    "            continue\n",
    "\n",
    "        try:\n",
    "            root = ElementTree.fromstring(html)\n",
    "        except ElementTree.ParseError:\n",
    "            continue\n",
    "\n",
    "        ns = {\"s\": \"http://www.sitemaps.org/schemas/sitemap/0.9\"}\n",
    "\n",
    "        # Si es un sitemap index, buscar sub-sitemaps de productos\n",
    "        sitemap_urls = root.findall(\".//s:sitemap/s:loc\", ns)\n",
    "        if sitemap_urls:\n",
    "            for sm in sitemap_urls:\n",
    "                sm_url = sm.text\n",
    "                if not sm_url:\n",
    "                    continue\n",
    "                # Priorizar sitemaps que contengan \"product\"\n",
    "                if \"product\" in sm_url.lower() or \"supermercado\" in sm_url.lower():\n",
    "                    logger.info(\"  [Sitemap] Sub-sitemap de productos: %s\", sm_url)\n",
    "                    sub_html = hacer_request(\n",
    "                        sm_url,\n",
    "                        headers={\"Accept\": \"application/xml, text/xml\"},\n",
    "                        accept_html=True,\n",
    "                    )\n",
    "                    if sub_html and isinstance(sub_html, str):\n",
    "                        try:\n",
    "                            sub_root = ElementTree.fromstring(sub_html)\n",
    "                            for loc in sub_root.findall(\".//s:url/s:loc\", ns):\n",
    "                                if loc.text:\n",
    "                                    urls_producto.append(loc.text)\n",
    "                        except ElementTree.ParseError:\n",
    "                            pass\n",
    "\n",
    "                    if len(urls_producto) >= MAX_SITEMAP_PRODUCTS:\n",
    "                        break\n",
    "        else:\n",
    "            # Es un sitemap plano, extraer URLs directamente\n",
    "            for loc in root.findall(\".//s:url/s:loc\", ns):\n",
    "                if loc.text and \"/p/\" in loc.text.lower():\n",
    "                    urls_producto.append(loc.text)\n",
    "\n",
    "        if urls_producto:\n",
    "            break\n",
    "\n",
    "    return urls_producto[:MAX_SITEMAP_PRODUCTS]\n",
    "\n",
    "\n",
    "def scrape_producto_html(url: str, tienda: str) -> Optional[dict]:\n",
    "    \"\"\"Extrae datos de un producto individual desde su página HTML.\"\"\"\n",
    "    html = hacer_request(url, headers={\"Accept\": \"text/html\"}, accept_html=True)\n",
    "    if not html or not isinstance(html, str):\n",
    "        return None\n",
    "\n",
    "    # Intentar JSON-LD (schema.org Product)\n",
    "    match = re.search(\n",
    "        r'<script\\s+type=\"application/ld\\+json\">(.*?)</script>',\n",
    "        html,\n",
    "        re.DOTALL,\n",
    "    )\n",
    "    if match:\n",
    "        try:\n",
    "            ld = json.loads(match.group(1))\n",
    "            # Puede ser una lista o un objeto\n",
    "            if isinstance(ld, list):\n",
    "                ld = next((x for x in ld if x.get(\"@type\") == \"Product\"), ld[0] if ld else {})\n",
    "\n",
    "            if ld.get(\"@type\") == \"Product\" or \"name\" in ld:\n",
    "                nombre = ld.get(\"name\", \"\")\n",
    "                marca = \"\"\n",
    "                if isinstance(ld.get(\"brand\"), dict):\n",
    "                    marca = ld[\"brand\"].get(\"name\", \"\")\n",
    "                elif isinstance(ld.get(\"brand\"), str):\n",
    "                    marca = ld[\"brand\"]\n",
    "\n",
    "                precio = None\n",
    "                precio_lista = None\n",
    "                offers = ld.get(\"offers\", {})\n",
    "                if isinstance(offers, list) and offers:\n",
    "                    offers = offers[0]\n",
    "                if isinstance(offers, dict):\n",
    "                    precio = offers.get(\"price\") or offers.get(\"lowPrice\")\n",
    "                    precio_lista = offers.get(\"highPrice\")\n",
    "\n",
    "                if nombre:\n",
    "                    return {\n",
    "                        \"tienda\": tienda,\n",
    "                        \"categoria\": \"\",\n",
    "                        \"nombre\": nombre,\n",
    "                        \"marca\": marca,\n",
    "                        \"precio\": precio,\n",
    "                        \"precio_lista\": precio_lista,\n",
    "                        \"producto_id\": ld.get(\"sku\", ld.get(\"productID\", \"\")),\n",
    "                        \"url_producto\": url,\n",
    "                    }\n",
    "        except (json.JSONDecodeError, StopIteration):\n",
    "            pass\n",
    "\n",
    "    # Intentar __NEXT_DATA__\n",
    "    match = re.search(\n",
    "        r'<script\\s+id=\"__NEXT_DATA__\"\\s+type=\"application/json\">(.*?)</script>',\n",
    "        html,\n",
    "        re.DOTALL,\n",
    "    )\n",
    "    if match:\n",
    "        try:\n",
    "            data = json.loads(match.group(1))\n",
    "            pp = data.get(\"props\", {}).get(\"pageProps\", {})\n",
    "            prod = pp.get(\"product\") or pp.get(\"data\", {}).get(\"product\", {})\n",
    "            if prod and isinstance(prod, dict):\n",
    "                item = extraer_producto_vtex(prod, tienda, \"\", url.rsplit(\"/\", 1)[0])\n",
    "                if item:\n",
    "                    item[\"url_producto\"] = url\n",
    "                    return item\n",
    "        except json.JSONDecodeError:\n",
    "            pass\n",
    "\n",
    "    return None\n",
    "\n",
    "\n",
    "def scrape_via_sitemap(base_url: str, tienda: str) -> list[dict]:\n",
    "    \"\"\"Extrae productos usando el sitemap y luego scraping individual.\"\"\"\n",
    "    urls = obtener_urls_sitemap(base_url)\n",
    "    if not urls:\n",
    "        logger.warning(\"  No se encontraron URLs de productos en el sitemap\")\n",
    "        return []\n",
    "\n",
    "    logger.info(\"  [Sitemap] %d URLs de productos encontradas\", len(urls))\n",
    "    productos = []\n",
    "    for i, url in enumerate(urls):\n",
    "        if i > 0 and i % 20 == 0:\n",
    "            logger.info(\"  [Sitemap] Procesando %d/%d...\", i, len(urls))\n",
    "\n",
    "        prod = scrape_producto_html(url, tienda)\n",
    "        if prod:\n",
    "            productos.append(prod)\n",
    "\n",
    "        time.sleep(0.5)  # Ser amable con el servidor\n",
    "\n",
    "    return productos\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Estrategia 5: Dominio VTEX alternativo (*.vtex.app)\n",
    "# ---------------------------------------------------------------------------\n",
    "VTEX_APP_DOMAINS = {\n",
    "    \"exito\": \"https://exito.vtex.app\",\n",
    "    \"jumbo\": \"https://jumbocolombia.vtex.app\",\n",
    "    \"olimpica\": \"https://olimpica.vtex.app\",\n",
    "}\n",
    "\n",
    "\n",
    "def buscar_via_vtex_app(tienda: str, queries: list[str]) -> list[dict]:\n",
    "    \"\"\"\n",
    "    Algunos sitios VTEX tienen un dominio alternativo *.vtex.app\n",
    "    que no tiene la misma protección anti-bot.\n",
    "    \"\"\"\n",
    "    vtex_url = VTEX_APP_DOMAINS.get(tienda)\n",
    "    if not vtex_url:\n",
    "        return []\n",
    "\n",
    "    logger.info(\"  Intentando dominio VTEX alternativo: %s\", vtex_url)\n",
    "    productos = []\n",
    "\n",
    "    # Probar Catalog API en el dominio alternativo\n",
    "    for query in queries:\n",
    "        data = buscar_vtex_catalog(vtex_url, query, tienda, query.split(\"/\")[-1])\n",
    "        if data:\n",
    "            productos.extend(data)\n",
    "\n",
    "    if productos:\n",
    "        return productos\n",
    "\n",
    "    # Probar Intelligent Search en el dominio alternativo\n",
    "    for query in queries[:3]:  # Solo las primeras para no abusar\n",
    "        data = buscar_vtex_intelligent_search(vtex_url, query, tienda, query)\n",
    "        if data:\n",
    "            productos.extend(data)\n",
    "\n",
    "    return productos\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Configuración por tienda\n",
    "# ---------------------------------------------------------------------------\n",
    "CATEGORIAS_TIENDA = {\n",
    "    \"exito\": {\n",
    "        \"catalog_paths\": [\n",
    "            \"mercado/frutas-y-verduras\",\n",
    "            \"mercado/lacteos-huevos-y-refrigerados\",\n",
    "            \"mercado/despensa\",\n",
    "            \"mercado/carnes-y-pescados\",\n",
    "            \"mercado/bebidas\",\n",
    "        ],\n",
    "        \"search_queries\": [\"frutas\", \"leche\", \"arroz\", \"pollo\", \"agua\", \"pan\", \"aceite\"],\n",
    "        \"html_paths\": [\n",
    "            \"/mercado/frutas-y-verduras\",\n",
    "            \"/mercado/despensa\",\n",
    "            \"/mercado/bebidas\",\n",
    "        ],\n",
    "    },\n",
    "    \"jumbo\": {\n",
    "        \"catalog_paths\": [\n",
    "            \"frutas-y-verduras\",\n",
    "            \"lacteos-huevos-y-refrigerados\",\n",
    "            \"despensa\",\n",
    "            \"carnes-y-pescados\",\n",
    "            \"bebidas\",\n",
    "        ],\n",
    "        \"search_queries\": [\"frutas\", \"leche\", \"arroz\", \"pollo\", \"agua\"],\n",
    "        \"html_paths\": [\n",
    "            \"/frutas-y-verduras\",\n",
    "            \"/despensa\",\n",
    "            \"/bebidas\",\n",
    "        ],\n",
    "    },\n",
    "    \"olimpica\": {\n",
    "        \"catalog_paths\": [\n",
    "            \"supermercado/frutas-y-verduras\",\n",
    "            \"supermercado/lacteos-y-huevos\",\n",
    "            \"supermercado/despensa\",\n",
    "            \"supermercado/carnes\",\n",
    "            \"supermercado/bebidas\",\n",
    "        ],\n",
    "        \"search_queries\": [\"frutas\", \"leche\", \"arroz\", \"pollo\", \"agua\"],\n",
    "        \"html_paths\": [\n",
    "            \"/supermercado/frutas-y-verduras\",\n",
    "            \"/supermercado/despensa\",\n",
    "            \"/supermercado/bebidas\",\n",
    "        ],\n",
    "    },\n",
    "    \"alkosto\": {\n",
    "        \"catalog_paths\": [\n",
    "            \"supermercado/despensa\",\n",
    "            \"supermercado/bebidas\",\n",
    "            \"supermercado/lacteos-y-refrigerados\",\n",
    "            \"supermercado/frutas-y-verduras\",\n",
    "            \"supermercado/carnes-y-pescados\",\n",
    "        ],\n",
    "        \"search_queries\": [\"frutas\", \"leche\", \"arroz\", \"pollo\", \"agua\"],\n",
    "        \"html_paths\": [\n",
    "            \"/supermercado/despensa\",\n",
    "            \"/supermercado/bebidas\",\n",
    "        ],\n",
    "    },\n",
    "}\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Orquestador\n",
    "# ---------------------------------------------------------------------------\n",
    "def scrape_tienda(nombre: str, base_url: str) -> list[dict]:\n",
    "    config = CATEGORIAS_TIENDA.get(nombre, {})\n",
    "    if not config:\n",
    "        logger.warning(\"Sin configuración para '%s'\", nombre)\n",
    "        return []\n",
    "\n",
    "    todos: list[dict] = []\n",
    "\n",
    "    # --- Estrategia 1: Catalog API (ahora acepta 206) ---\n",
    "    logger.info(\"[1/5] Catalog API para %s...\", nombre.upper())\n",
    "    for path in config.get(\"catalog_paths\", []):\n",
    "        categoria = path.split(\"/\")[-1]\n",
    "        productos = buscar_vtex_catalog(base_url, path, nombre, categoria)\n",
    "        if productos:\n",
    "            logger.info(\"    ✓ %d productos (%s)\", len(productos), categoria)\n",
    "            todos.extend(productos)\n",
    "\n",
    "    if todos:\n",
    "        return todos\n",
    "\n",
    "    # --- Estrategia 2: Intelligent Search ---\n",
    "    logger.info(\"[2/5] Intelligent Search para %s...\", nombre.upper())\n",
    "    for query in config.get(\"search_queries\", []):\n",
    "        productos = buscar_vtex_intelligent_search(base_url, query, nombre, query)\n",
    "        if productos:\n",
    "            logger.info(\"    ✓ %d productos ('%s')\", len(productos), query)\n",
    "            todos.extend(productos)\n",
    "\n",
    "    if todos:\n",
    "        return todos\n",
    "\n",
    "    # --- Estrategia 3: Dominio VTEX alternativo (*.vtex.app) ---\n",
    "    logger.info(\"[3/5] Dominio VTEX alternativo para %s...\", nombre.upper())\n",
    "    productos = buscar_via_vtex_app(nombre, config.get(\"catalog_paths\", []))\n",
    "    if productos:\n",
    "        logger.info(\"    ✓ %d productos vía vtex.app\", len(productos))\n",
    "        todos.extend(productos)\n",
    "\n",
    "    if todos:\n",
    "        return todos\n",
    "\n",
    "    # --- Estrategia 4: __NEXT_DATA__ ---\n",
    "    logger.info(\"[4/5] __NEXT_DATA__ para %s...\", nombre.upper())\n",
    "    for path in config.get(\"html_paths\", []):\n",
    "        categoria = path.strip(\"/\").split(\"/\")[-1]\n",
    "        productos = buscar_nextdata(base_url, path, nombre, categoria)\n",
    "        if productos:\n",
    "            logger.info(\"    ✓ %d productos (%s)\", len(productos), categoria)\n",
    "            todos.extend(productos)\n",
    "\n",
    "    if todos:\n",
    "        return todos\n",
    "\n",
    "    # --- Estrategia 5: Sitemap + scraping individual ---\n",
    "    logger.info(\"[5/5] Sitemap + scraping HTML para %s...\", nombre.upper())\n",
    "    productos = scrape_via_sitemap(base_url, nombre)\n",
    "    if productos:\n",
    "        logger.info(\"    ✓ %d productos vía sitemap\", len(productos))\n",
    "        todos.extend(productos)\n",
    "\n",
    "    return todos\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Ejecución principal\n",
    "# ---------------------------------------------------------------------------\n",
    "def main() -> pd.DataFrame:\n",
    "    tiendas = leer_urls(ARCHIVO_LISTA)\n",
    "    todos_los_productos: list[dict] = []\n",
    "\n",
    "    for nombre, url in tiendas.items():\n",
    "        logger.info(\"=\" * 60)\n",
    "        logger.info(\"SCRAPING: %s (%s)\", nombre.upper(), url)\n",
    "        logger.info(\"=\" * 60)\n",
    "\n",
    "        productos = scrape_tienda(nombre, url)\n",
    "        logger.info(\"→ %d productos totales de %s\\n\", len(productos), nombre.upper())\n",
    "        todos_los_productos.extend(productos)\n",
    "\n",
    "    # Crear DataFrame consolidado\n",
    "    df = pd.DataFrame(todos_los_productos)\n",
    "\n",
    "    if df.empty:\n",
    "        logger.warning(\n",
    "            \"No se extrajeron productos. Posibles causas:\\n\"\n",
    "            \"  - Los sitios bloquearon las peticiones\\n\"\n",
    "            \"  - Las APIs cambiaron de estructura\\n\"\n",
    "            \"  - Problemas de red\"\n",
    "        )\n",
    "        return pd.DataFrame(columns=[\n",
    "            \"tienda\", \"categoria\", \"nombre\", \"marca\",\n",
    "            \"precio\", \"precio_lista\", \"producto_id\", \"url_producto\",\n",
    "        ])\n",
    "\n",
    "    # Limpieza\n",
    "    df[\"precio\"] = pd.to_numeric(df[\"precio\"], errors=\"coerce\")\n",
    "    df[\"precio_lista\"] = pd.to_numeric(df[\"precio_lista\"], errors=\"coerce\")\n",
    "\n",
    "    # Eliminar duplicados\n",
    "    antes = len(df)\n",
    "    df = df.drop_duplicates(subset=[\"tienda\", \"producto_id\"], keep=\"first\")\n",
    "    if len(df) < antes:\n",
    "        logger.info(\"Duplicados eliminados: %d → %d registros\", antes, len(df))\n",
    "\n",
    "    # Resumen\n",
    "    logger.info(\"\\n\" + \"=\" * 60)\n",
    "    logger.info(\"RESUMEN FINAL\")\n",
    "    logger.info(\"=\" * 60)\n",
    "    logger.info(\"Total productos únicos: %d\", len(df))\n",
    "    logger.info(\"Productos por tienda:\\n%s\", df[\"tienda\"].value_counts().to_string())\n",
    "    if df[\"precio\"].notna().any():\n",
    "        logger.info(\n",
    "            \"Rango de precios por tienda:\\n%s\",\n",
    "            df.groupby(\"tienda\")[\"precio\"]\n",
    "            .agg([\"count\", \"min\", \"max\", \"mean\"])\n",
    "            .round(0)\n",
    "            .to_string(),\n",
    "        )\n",
    "    logger.info(\"\\nPrimeras filas:\\n%s\", df.head(10).to_string())\n",
    "\n",
    "    # Guardar\n",
    "    output_csv = \"productos_supermercados.csv\"\n",
    "    df.to_csv(output_csv, index=False, encoding=\"utf-8-sig\")\n",
    "    logger.info(\"\\nDatos guardados en: %s\", output_csv)\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    df = main()\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# NOTAS Y TROUBLESHOOTING\n",
    "# ---------------------------------------------------------------------------\n",
    "#\n",
    "# CAMBIOS v3 vs v2:\n",
    "#   - HTTP 206 ahora se acepta como respuesta válida (VTEX lo usa para\n",
    "#     indicar contenido parcial con paginación)\n",
    "#   - Se agregó dominio *.vtex.app como alternativa (menos protección)\n",
    "#   - Se agregó scraping vía sitemap.xml + JSON-LD para sitios no-VTEX\n",
    "#   - Se unificó la extracción de datos VTEX en una sola función\n",
    "#\n",
    "# SI ÉXITO NO DEVUELVE DATOS:\n",
    "#   Éxito (exito.com) usa protección Cloudflare agresiva. El dominio\n",
    "#   alternativo exito.vtex.app puede funcionar mejor. Si no:\n",
    "#     1. Abre exito.com en tu navegador\n",
    "#     2. Abre DevTools (F12) → Network → busca peticiones a /api/\n",
    "#     3. Copia las cookies de sesión\n",
    "#     4. Agrégalas a HEADERS_BASE: {\"Cookie\": \"tu_cookie_aquí\"}\n",
    "#\n",
    "# SI ALKOSTO NO DEVUELVE DATOS:\n",
    "#   Alkosto no usa VTEX como los demás. Opciones:\n",
    "#     1. El sitemap debería funcionar si existe en /sitemap.xml\n",
    "#     2. Busca su API en DevTools: abre la web, filtra peticiones XHR,\n",
    "#        y busca endpoints que devuelvan JSON con productos\n",
    "#     3. Usa Selenium/Playwright como último recurso\n",
    "#\n",
    "# DESCUBRIR CATEGORÍAS VTEX:\n",
    "#   GET {base_url}/api/catalog_system/pub/category/tree/3\n",
    "#\n",
    "# RATE LIMITING: Aumenta DELAY_ENTRE_REQUESTS si ves errores 429.\n",
    "# ---------------------------------------------------------------------------"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b1bff97",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "web_scrapping",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
